### ISSUE TITLE
Change docker-flink logo

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#27]
For trademark reasons we had to change the logo of this repository, I want to
propose to reuse the logo of the blog post as the official docker-flink logo.

https://activerain-store.s3.amazonaws.com/image_store/uploads/8/7/6/3/9/ar12988558393678.JPG

**Comment by patricklucas** [comment]
Sure, why not.

Do you know if there's any issue using the Flink logo [here](https://github.com/docker-flink/docs/tree/eead56c49df1d9bc0fbfb1c7f2c432be73c1cd3a/flink)? Since the software in the image is Flink and it's in the context of a link to Wikipedia where the logo is also in-use, it might be fine, but on the other hand, lawyers have complained and threatened about less...

**Comment by iemejia** [comment]
I don't think there should be an issue for the reasons you mention and also because other Apache projects include the logo in the documentation, see:

https://github.com/docker-library/docs/tree/master/solr
https://github.com/docker-library/docs/tree/master/cassandra
https://github.com/docker-library/docs/tree/master/storm

So I suppose we can keep it and change it only if we are requested to do so.

**Comment by patricklucas** [comment]
Cool, closing this then.
