### ISSUE TITLE
RocksDB state backend causes segfault on Alpine images again

### ISSUE THREAD

**Issue by lragnarsson** [docker-flink/docker-flink#37]
Seems like the problem in #14 has reappeared at least for 1.4.1-hadoop27-scala_2.11-alpine.

Anyone else experience this?

**Comment by iemejia** [comment]
I confirm this is an issue, it seems to be a regression related to libc6-compat on alpine:3.7. Not sure what would be the best way to proceed, we can repackage libc compatibility by using https://github.com/sgerrand/alpine-pkg-glibc as some Java based containers do, or just remove support for the alpine images until fixed upstream. @patricklucas WDYT ?

**Comment by patricklucas** [comment]
I'm not super enthusiastic about keeping alpine support given these persistent issues. The alpine-based image is ~37% smaller than the debian-based image, but that's the only benefit as far as I can tell.

Since users running in production environments are likely building their own images anyway, I'm not sure maintaining support for alpine-based images is all that useful.

We could keep building the alpine-based Dockerfiles in this repo for interested users, but just not publish them to Docker Hub.

**Comment by patricklucas** [comment]
@iemejia do you know if this has been fixed upstream? If not, I would move forward with removing the alpine images.

**Comment by iemejia** [comment]
Yes it was solved for Alpine 3.7 and I just tested the latest version 3.8 and it seems to work. So we should be covered once our images are regenerated (they just updated openjdk:8-jre-alpine yesterday to be based on the 'new' alpine 3.8).

**Comment by patricklucas** [comment]
👍
