### ISSUE TITLE
Add multi arch images for all the architectures supported by openjdk

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#41]

**Comment by patricklucas** [comment]
I wonder if we can just add blanket support for all the architectures supported by the official openjdk images, since that's what we're downstream of.

We add a few binary packages, but they should still be available from the debian/alpine upstreams, and gosu seems to support all the relevant architectures too.

**Comment by iemejia** [comment]
Agree about covering all architectures supported by openjdk (will rename this issue accordingly). But what a mess with the arm32 stuff, thanks for finding that script, looks really useful indeed for the goal.

(slightly unrelated) Just for future reference there is a docker image to check the supported platforms in multi arch docker images. e.g. `docker run --rm mplatform/mquery flink`

**Comment by iemejia** [comment]
This was autoclosed but well we need to publish the multiarch images first, giving my first try to do it if you agree @patricklucas.

**Comment by patricklucas** [comment]
Sure, go for it. Yesterday I pushed to docker-flink/official-images master but waited for this to be closed before opening a PR upstream, but feel free to use that to double-check your own changes, overwrite the commit (or push to a branch), and then open the PR upstream.

As far as Flink 1.5.1, I've actually been holding off since there was a regression and I think 1.5.2 will be released today or tomorrow, and I considered just skipping this mildly broken release. Feel free to handle the upcoming releases and just add me to the PRs.

**Comment by iemejia** [comment]
@patricklucas small question, it seems the PR was merged but the images are not published yet, do I have to do some extra manual step now to have the images published in docker hub, or just wait? How can I see the progress if so. Thanks.

**Comment by patricklucas** [comment]
Looks like they're available now. I've found that it usually takes no more than 24 hours after opening the PR for the images to be available.

**Comment by patricklucas** [comment]
Hmm, though it's possible that not all the images could be built, since it seems that Apache doesn't keep around older releases on its dist server that gets mirrored—I only see 1.3.3, 1.4.2, and 1.5.1 on [there](https://apache.org/dist/flink/). They _are_ however available on the "archive" subdomain, so we could I suppose use it instead, though maybe that's frowned upon?

**Comment by patricklucas** [comment]
Hmm, though it's possible that not all the images could be built, since it seems that Apache doesn't keep around older releases on its dist server that gets mirrored—I only see 1.3.3, 1.4.2, and 1.5.1 on [there](https://apache.org/dist/flink/). They _are_ however available on the ["archive" subdomain](https://archive.apache.org/dist/flink/), so we could I suppose use it instead, though maybe that's frowned upon?

**Comment by patricklucas** [comment]
Also, looks like 1.5.1 won't be out this week, so I'll go ahead and update to move things along here.

**Comment by iemejia** [comment]
Things look ready on docker hub so closing.
