### ISSUE TITLE
Use Java 11

### ISSUE THREAD

**Issue by SMadani** [docker-flink/docker-flink#58]
Java 8 will be end-of-life in 2019/2020, and Java 11 was released in September 2018 which is long-term support. Currently written programs in Java 9 and later don't work due to the Flink image using an outdated version of Java. Is there any reason why Java 8 is still being used?

**Comment by patricklucas** [comment]
Java 8 is used because [Flink itself still depends on Java 8](https://flink.apache.org/faq.html#what-are-the-prerequisites-to-use-flink). When newer Java becomes supported by Flink, we'll update these images.

[FLINK-8033](https://issues.apache.org/jira/browse/FLINK-8033) tracks support for Java 9, and is targeted for [Flink 1.7.0](https://issues.apache.org/jira/projects/FLINK/versions/12343585) which should be released pretty soon. I can't find an issue for Java 11 support, but I imagine it will be added to the roadmap once Java 9 support is finalized.

**Comment by SMadani** [comment]
Java 9 has been end of life for many months now, I'm not sure why anyone would want to support it. The "support path" should be quite clear: Java 11 then Java 15.

**Comment by patricklucas** [comment]
You should be taking this up with the Flink community on the mailing list or issue tracker, not the Dockerfile repo.

Nevertheless, supporting Java 9 is a necessary step on the way to current Java support—it would be difficult to support Java 11 before it works on Java 9—and this work alone has been quite involved and ongoing since long before either Java 10 or Java 11 were released.

**Comment by SMadani** [comment]
I've raised the [issue](FLINK-10725) on JIRA. Also my point was that supporting Java 11 should require no extra work if supporting Java 9, it's basically a version change so it makes no sense to call it "Java 9" support when Java 9 practically doesn't exist anymore.

**Comment by patricklucas** [comment]
Thanks. I'm going to close this for now, but upgrading these images will be a priority for any later Java support from Flink whenever that occurs, so a new issue can be opened at that time.
