### ISSUE TITLE
Support configuration properties available as env vars in Docker 

### ISSUE THREAD

**Issue by hustclf** [docker-flink/docker-flink#71]
Is there any plan for flink docker image to support overrite configurations via env vars ?

I am using kubernetes to deploy a flink session cluster. When I want to change `taskmanager.heap.size`, I have to use `Configmap` to overrite `flink-conf.yaml` in container.

I would like to contribute the feature if the idea is approved.

**Comment by patricklucas** [comment]
This is something we've considered, but I would greatly prefer anything like this to be supported by Flink upstream first, instead of implementing it as an additional configuration method by the Docker images alone.

Flink already has some fragmentation with respect to how it's configured, and I'm trying hard not to have the Docker images contribute to it. You might consider searching for/opening a ticket on [Apache Flink JIRA](https://issues.apache.org/jira/browse/FLINK) or starting a discussion on the [user mailing list](https://flink.apache.org/community.html#mailing-lists).

**Comment by hustclf** [comment]
Thanks for your detailed answer and your advice.  :)
